# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$shell\
$username\
$directory\
$git_branch\
$character\
"""

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
[character]
success_symbol = "⮞"
error_symbol = "[x](bold red)"

[git_branch]
style = "fg:#ffa500"
format = 'on [ $branch]($style) '

# Add a custom shell indicator
[shell]
zsh_indicator = '[󰣇](bold #3ea4ff) '
disabled = false

[username]
style_user = 'white bold'
style_root = 'blue bold'
format = '[$user]($style) '
disabled = false
show_always = true
