[accessibility]
ui_scale = 1.2000000104308128

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.9499999787658453
    center = [ "audio_visualizer", "widget_3" ]
    contact_shadow = true
    end = [ "tray", "privacy", "widget", "gamermode", "group:g1", "group:g3", "network", "clock", "session" ]
    margin_ends = 0
    padding = 13
    radius = 0
    radius_bottom_left = 0
    radius_bottom_right = 0
    scale = 1.2000000104308128
    show_on_workspace_switch = false
    start = [ "control-center", "workspaces", "group:g2", "group:g4" ]
    thickness = 40
    widget_spacing = 10

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = ""
        enabled = true
        fill = "primary"
        id = "g2"
        members = [ "cpu", "temp", "ram", "network_rx", "network_tx" ]
        opacity = 0.0
        padding = 18.0

        [[bar.default.capsule_group]]
        accordion = true
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "bar", "notifications", "clipboard", "bluetooth" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "volume", "brightness" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "widget_2", "screenshot" ]
        opacity = 1.0
        padding = 6.0

[calendar]
refresh_minutes = 50

[control_center]
sidebar = "full"
width = 810

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "dark_mode"

    [[control_center.shortcuts]]
    type = "session"

[desktop_widgets]
schema_version = 1
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000006"
]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 80.0
    box_width = 248.0
    cx = 1756.0
    cy = 144.0
    enabled = false
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = -0.0
    type = "label"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = true
        description = ""
        opacity = 1.0
        shadow = false
        title = "Focus."

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 144.0
    box_width = 272.0
    cx = 1760.0
    cy = 264.0
    enabled = false
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = true
        clock_style = "digital"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 264.0
    box_width = 272.0
    cx = 1480.0
    cy = 236.0
    enabled = false
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "noctalia/timer:desktop"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 408.0
    box_width = 824.0
    cx = 1476.0
    cy = 864.0
    enabled = false
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sticker"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background_radius = 16
        image_path = "/home/fitrah/Pictures/screenshot_20260805_150800-region.png"
        opacity = 1.0

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 112.0
    box_width = 696.0
    cx = 1328.0
    cy = 392.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = -0.0
    type = "label"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background = false
        opacity = 1.0
        title = "Act with conviction,"

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 112.0
    box_width = 768.0
    cx = 1440.0
    cy = 456.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "label"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        background = false
        opacity = 1.0
        title = " update with humility."

[dock]
background_opacity = 0.99999997764825821
concave_edge_corners = false
cross_axis_padding = 0
enabled = true
icon_size = 65
inactive_opacity = 0.89999997988343239
inactive_scale = 1.0
item_spacing = 0
launcher_custom_image = "/home/fitrah/.local/share/icons/custom/Arch_Linux_Z8FjPTQ5fS_icns-c903f957b2_512x512x32.png"
launcher_position = "start"
main_axis_padding = 10
pinned = [
    "zen",
    "dev.zed.Zed",
    "kitty",
    "discord",
    "spotify-launcher",
    "org.vinegarhq.Sober",
    "org.vinegarhq.Vinegar",
    "obsidian"
]
radius = 0
radius_bottom_left = 20
radius_bottom_right = 20
radius_top_left = 20
radius_top_right = 20
show_dots = true

[hot_corners]
delay_ms = 2000

[idle]
pre_action_fade_seconds = 0.0

[location]
address = "Gowa, Indonesia"

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = false
schema_version = 1
widget_order = [
    "lockscreen-login-box@WAYLAND-1",
    "lockscreen-widget-0000000000000008",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000009"
]

    [lockscreen_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1"]
    box_height = 196.0
    box_width = 727.0
    cx = 379.5
    cy = 352.0
    output = "WAYLAND-1"
    placement_height = 534.0
    placement_width = 759.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 600.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "on_secondary"
        background_opacity = 0.0
        background_radius = 0.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 32.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 64.0
    box_width = 152.0
    cx = 1836.0
    cy = 1136.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.0
        background_padding = 0
        background_radius = 0
        clock_style = "digital"
        color = "on_surface"
        font_family = ""
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000008]
    box_height = 344.0
    box_width = 416.0
    cx = 960.0
    cy = 484.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sticker"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000008.settings]
        background = false
        image_path = "/home/fitrah/Downloads/kucingitem.png"
        opacity = 1.0

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000009]
    box_height = 24.0
    box_width = 200.0
    cx = 1800.0
    cy = 1164.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000009.settings]
        background = false
        color = "error"
        shadow = false
        title = "Don't touch my laptop"

[notification]
background_opacity = 0.99999997764825821
layer = "overlay"

[osd]
background_opacity = 0.99999997764825821
keyboard_layout = false
position = "bottom_center"
position_vertical = "bottom_center"

[plugin_settings."alexander/screen-toolkit"]
record-audio-out = true

[plugin_settings."blackbartblues/keymap"]
merge_similar = true

[plugin_settings."kenn/keybind-cheatsheet"]
compositor = "mango"
show_actions = true

[plugin_settings."noctalia/mpvpaper"]
picker_placement = "floating"
video_directory = "/home/fitrah/Pictures/Wallpapers"

[plugin_settings."noctalia/screen_recorder"]
directory = ""
quality = "high"
video_source = "portal"

[plugin_settings."noctalia/translator"]
target_lang = "id"

[plugin_settings."noctalia/wallhaven"]
browser_placement = "attached"

[plugin_settings."yuuto/calculator"]
panel_placement = "floating"
panel_position = "center"

[plugins]
enabled = [
    "thepunkoff/pomodoro",
    "yuuto/calculator",
    "nomadcxx/gamer-mode",
    "noctalia/timer",
    "me/hello",
    "me/mau-ngoding",
    "nightwatch75/dns-switcher",
    "alexander/screen-toolkit"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "/home/fitrah/Developments/PluginNoctalia"
    name = "my-plugin"

[shell]
avatar_path = "/home/fitrah/Downloads/kingbee.jpg"
polkit_agent = true
screen_time_enabled = true
telemetry_enabled = true
ui_scale = 1.1499999999999999

    [shell.launcher]
    compact = true
    session_search = true

        [shell.launcher.providers.emoji]
        global = true

        [shell.launcher.providers.windows]
        global = true

    [shell.panel]
    list_item_background = true
    open_near_click_control_center = true

    [shell.screen_corners]
    size = 30

    [shell.screenshot]
    confirm_region = true

[theme]
builtin = "Kanagawa"
community_palette = "Kemuri Susu"
custom_palette = "custom"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kitty", "mango", "niri", "qt" ]
    community_ids = [ "spicetify", "neovim", "obsidian", "zed", "rofi", "papirus-icons", "yazi", "zathura" ]

        [theme.templates.user.noctwhspr_mic_osd]
        input_path = "/home/fitrah/.config/noctalia/templates/noctwhspr-mic-osd.css"
        output_path = "/home/fitrah/.config/hyprwhspr/theme/mic-osd.css"

[wallpaper]
directory = "/home/fitrah/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/fitrah/Pictures/Wallpapers/4a6841adbaafdabc.jpg"

    [wallpaper.last]
    path = "/home/fitrah/Pictures/Wallpapers/4a6841adbaafdabc.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/fitrah/Pictures/Wallpapers/4a6841adbaafdabc.jpg"

    [[wallpaper.favorite]]
    community_palette = "Kemuri Susu"
    palette_source = "community"
    path = "/home/fitrah/Pictures/Wallpapers/4a6841adbaafdabc.jpg"
    theme_mode = "dark"

[widget.AutoHide]
glyph = "eye-filled"
tooltip = "Auto Hide "
type = "custom_button"

    [widget.AutoHide.actions]
    left = "exec noctalia msg bar-auto-hide-set on bar-blur"
    right = "exec noctalia msg bar-auto-hide-set off bar-blur"

[widget.FIle]
glyph = ""
label = "Finder"
type = "custom_button"

[widget.audio_visualizer]
bands = 128
width = 111

[widget.bar]
type = "yuuto/calculator:bar"

[widget.bongocat]
capsule = true
capsule_group = "LEFT"
input_device = ""
script = "scripts/bongocat.lua"
type = "scripted"

[widget.brightness]
enabled = true

[widget.cat_2]
type = "noctalia/bongocat:cat"

[widget.clock]
color = "error"
scale = 1.1000000000000001

[widget.control-center]
glyph = "brand-apple-filled"
scale = 1.3

[widget.cpu]
capsule_border = "primary"
capsule_fill = "on_secondary"
capsule_opacity = 0.75
stat = "cpu_temp"

[widget.gamermode]
type = "nomadcxx/gamer-mode:gamermode"

[widget.media]
capsule = true
hide_when_no_media = true

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.mpvpaper_2]
type = "noctalia/mpvpaper:mpvpaper"

[widget.network]
show_label = false

[widget.notes]
type = "noctalia/notes:notes"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.recorder_2]
type = "noctalia/screen_recorder:recorder"

[widget.screen_recorder]
script = "scripts/screen_recorder.lua"
type = "scripted"

[widget.spacer_2]
type = "spacer"

[widget.status]
type = "goodroot/noctwhspr:status"

[widget.sysmon]
stat = "net_tx"

[widget.temp]
stat = "gpu_temp"

[widget.todo]
scale = 1.2
type = "nightwatch75/todo:todo"

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.widget]
type = "thepunkoff/pomodoro:widget"

[widget.widget_2]
type = "alexander/screen-toolkit:widget"

[widget.widget_3]
type = "blackbartblues/keymap:widget"

[widget.workspaces]
active_pill_size = 2.5
capsule = true
capsule_group = "LEFT"
capsule_padding = 1
hide_when_empty = true
inactive_pill_size = 1.25
pill_scale = 0.80000000000000004
scale = 1.1500000000000001
