# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131313ff
bordercolor = 0x919191ff
dropcolor = 0x62d3ff80
splitcolor = 0xc5c2eaff
focuscolor = 0x62d3ffff
maximizescreencolor = 0xb4cad5ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xc5c2eaff
globalcolor = 0x004d63ff
overlaycolor = 0x354a53ff
jump_label_decorate_fg_color = 0xe2e2e2ff
jump_label_decorate_bg_color = 0x2a2a2aff
jump_label_decorate_focus_fg_color = 0x003545ff
jump_label_decorate_focus_bg_color = 0x62d3ffff
jump_label_decorate_border_color = 0x919191ff
group_bar_decorate_fg_color = 0xe2e2e2ff
group_bar_decorate_bg_color = 0x2a2a2aff
group_bar_decorate_focus_fg_color = 0x003545ff
group_bar_decorate_focus_bg_color = 0x62d3ffff
group_bar_decorate_border_color = 0x919191ff
