# Laptop display
# monitorrule=name:^eDP-1$,width:1920,height:1200,refresh:60,x:0,y:10
 monitorrule=name:^eDP-1$,width:1920,height:1200,refresh:60,scale:1,x:0,y:0

# layout support:
# tile,scroller,monocle,grid,deck,center_tile,vertical_tile,right_tile,vertical_scroller,vertical_grid,vertical_deck,dwindle,fair,vertical_fair
# i like this layout cuz i use laptop XD : scroller, monocle, vertical_scroller
# circle_layout=scroller,vertical_scroller,deck
circle_layout=tile,scroller,monocle,grid,deck,center_tile,vertical_tile,right_tile,vertical_scroller,vertical_grid,vertical_deck,dwindle,fair,vertical_fair
# Tag Rules
tagrule=id:*,layout_name:scroller
# game
tagrule=id:8,no_render_border:1,scroller_default_proportion:1

# Window Rules
windowrule=tags:9,appid:discord,shield_when_capture:0
windowrule=tags:1,appid:zen
windowrule=tags:8,appid:org.vinegarhq.Sober,isfullscreen:1,isopensilent:1,istagsilent:1

# Layer Rules
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi

# Scratchpad
windowrule=isnamedscratchpad:1,width:1280,height:800,title:yazi
windowrule=isnamedscratchpad:1,width:1280,height:800,title:terminal
# Disable client-side decorations
windowrule=allow_csd:1,appid:firefox
# tagrule=id:1,no_hide:1,no_render_border:1
