# Laptop display
# monitorrule=name:^eDP-1$,width:1920,height:1200,refresh:60,x:0,y:10
 monitorrule=name:^eDP-1$,width:1920,height:1200,refresh:60,scale:1,x:0,y:0

# layout support:
# tile,scroller,monocle,grid,deck,center_tile,vertical_tile,right_tile,vertical_scroller,vertical_grid,vertical_deck,dwindle,fair,vertical_fair
# i like this layout cuz i use laptop XD : scroller, monocle, vertical_scroller
# circle_layout=scroller,vertical_scroller,deck
circle_layout=tile,scroller,monocle,grid,deck,center_tile,vertical_tile,right_tile,vertical_scroller,vertical_grid,vertical_deck,dwindle,fair,vertical_fair
# Tag Rules
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# Window Rules
#windowrule=isopensilent:1,appid:robloxstudiobeta.exe
#windowrule=isopensilent:1,appid:RobloxStudio
#windowrule=isopensilent:1,appid:Roblox Studio
#windowrule=animation_type_open:none,title:RobloxStudio
#windowrule=animation_type_close:none,title:RobloxStudio
#windowrule=allow_csd:1,appid:robloxstudiobeta.exe
#windowrule=tags:2,appid:robloxstudiobeta.exe

# Layer Rules
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi

windowrule=isnamedscratchpad:1,width:1280,height:800,title:yazi
windowrule=isnamedscratchpad:1,width:1280,height:800,title:terminal
